server:
  port: 9090
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url:  jdbc:mysql://localhost:3306/springboot-vue?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
mybatis-plus:
  configuration:
    local-cache-scope: statement
    cache-enabled: false
    map-underscore-to-camel-case: true